### ISSUE TITLE
アプリの概形を決める

### ISSUE THREAD

**Issue by N4U74** [Marumo-k18188am/challecara-git#2]

**Comment by Marumo-k18188am** [comment]
ログイン
・ログインフォーム

スケジューリング+イベント登録(メイン)
・カレンダー
・メニューバー
　・アカウントボタン
　・通知リンク
　・カレンダーリンク
　・(マップリンク)
　・コミュニティリンク

アカウント
・ユーザー情報の表示
・(ユーザー情報編集)
・ログアウトボタン

通知
・イベントの検索結果→詳細

マップ
・自分の趣味に合う施設(GoogleMap)

コミュニティ
・グループ欄
・+alpha
